FROM postgres:latest
LABEL authors="mukimmanan"

ARG DATABASE_NAME="patients_db"
ARG PASSWORD="DUMMY_PWD"
ARG USER="DUMMY_USER"


ENV POSTGRES_USER=${USER}
ENV POSTGRES_PASSWORD=${PASSWORD}
ENV POSTGRES_DB=${DATABASE_NAME}


EXPOSE 5432